import { SCROLLING_DEBOUNCE_MS } from "../../shared/virtualShared/constants.ts";

const DEFAULT_OVERSCAN_ROWS = 3;
const DEFAULT_OVERSCAN_COLS = 3;

export { DEFAULT_OVERSCAN_COLS, DEFAULT_OVERSCAN_ROWS, SCROLLING_DEBOUNCE_MS };
